USE ROLE SECURITYADMIN;
CREATE USER IF NOT EXISTS Z2S_USER
	PASSWORD 			 = $$*****$$
;
ALTER USER Z2S_USER SET
    COMMENT              = $$Zero To Snowflake User$$
    LOGIN_NAME           = Z2S_USER
    DISPLAY_NAME         = Z2S_USER
    DEFAULT_ROLE         = PC_FIVETRAN_ROLE
	DEFAULT_WAREHOUSE    = PC_FIVETRAN2_WH
    DEFAULT_NAMESPACE    = SALESFORCE_Z2S
;
GRANT ROLE PC_FIVETRAN_ROLE TO USER Z2S_USER;
SHOW GRANTS TO USER Z2S_USER;
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS PC_FIVETRAN2_WH WITH
    INITIALLY_SUSPENDED                 = TRUE
;
ALTER WAREHOUSE PC_FIVETRAN2_WH SET
    WAREHOUSE_SIZE                      = XSMALL
    AUTO_SUSPEND                        = 1
    AUTO_RESUME                         = TRUE
;
GRANT OWNERSHIP ON WAREHOUSE PC_FIVETRAN2_WH TO ROLE PC_FIVETRAN_ROLE;